const initialState = {
  authenticated: '',
  firstName: '',
  lastName: '',
  status: '',
  newEntry: [],
  newEntryError: [],
  singleEntry: [],
  singleEntryError: [],
  editedEntry: [],
  editedEntryError: [],
  deletedEntry: [],
  deletedEntryError: [],
  existingReminder: [],
  existingReminderError: [],
  newReminder: [],
  newReminderError: [],
  deletedReminder: [],
  deletedReminderError: [],
  entries: [],
  entriesError: [],
  error: [],
};

export default initialState;
